[workspace]
resolver = "2"
members = [
    "crates/abi",
    "crates/bloxroute",
    "crates/fourmeme",
    "crates/logging",
    "crates/pancake-v2",
    "crates/rpc",
    "crates/sender",
    "crates/telegram",
    "crates/transaction-stream",
    "crates/types",
    "crates/price-track",
    "crates/price-query",
    "services/auto-sell-bot",
    "services/migrate-bot", "services/price-bot", "services/mempool-migrate", "crates/auto-sell", "services/mempool-special-addr",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"
readme = "./README.md"

[workspace.dependencies]
alloy = { version = "1.0.41", features = ["full"] }
tokio = { version = "1.48.0", features = ["full"] }
anyhow = { version = "^1.0.100" }
tracing = "0.1.41"
futures = "0.3.31"
dotenvy = "0.15.7"
serde_json = "1.0.145"
reqwest = "0.12.24"
regex = "1.12.2"
once_cell = "1.21.3"
iceoryx2 = "0.7.0"
futures-util = "0.3.31"

rpc = { path = "crates/rpc" }
sender = { path = "crates/sender" }
pancake-v2 = { path = "crates/pancake-v2" }
fourmeme = { path = "crates/fourmeme" }
bloxroute = { path = "crates/bloxroute" }
abi = { path = "crates/abi" }
logging = { path = "crates/logging" }
transaction-stream = { path = "crates/transaction-stream" }
types = { path = "crates/types" }
price-track = { path = "crates/price-track" }
price-query = { path = "crates/price-query" }


[profile.release]
overflow-checks = true

[profile.dev]
overflow-checks = true
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
