[package]
name = "bloxroute"
version.workspace = true
edition.workspace = true
license.workspace = true
readme.workspace = true

[dependencies]
reqwest = { workspace = true }
anyhow = { workspace = true }
serde_json = { workspace = true }
